Update HmacSHA256Signer.java
To avoid java.lang.NoSuchMethodError: org.apache.commons.codec.binary.Hex.encodeHexString on Android due to different versions of commons codec.